# -*- coding: utf-8 -*-
"""Uri_1011.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

r=float(input())
pi=3.14159
VOLUME=(4/3)*pi*r**3
print("VOLUME = {:.3f}".format(VOLUME))