# -*- coding: utf-8 -*-
"""Uri_1017.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

tempo=int(input())
veloci=int(input())
litros=tempo*veloci/12
print('{:.3f}'.format(litros))