# -*- coding: utf-8 -*-
"""Uri_1049.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HVuUV0P4lfD2K12nDpHlus7ibCikFqWG
"""

tipo=input()
if tipo=="vertebrado":
  tipo1=input()
  if tipo1=="ave":
    aliment=input()
    if aliment=="carnivoro":
      print("aguia")
    if aliment=="onivoro":
      print("pomba")
  if tipo1=="mamifero":
    aliment=input()
    if aliment=="onivoro":
      print("homem")
    if aliment=="herbivoro":
      print("vaca")
if tipo=="invertebrado":
  tipo1=input()
  if tipo1=="inseto":
    aliment=input()
    if aliment=="hematofago":
      print("pulga")
    if aliment=="herbivoro":
      print("lagarta")
  if tipo1=="anelideo":
    aliment=input()
    if aliment=="hematofago":
      print("sanguessuga")
    if aliment=="onivoro":
      print("minhoca")