# -*- coding: utf-8 -*-
"""Uri_1004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

a=int(input())
b=int(input())
PROD=a*b
print("PROD =",PROD)