# -*- coding: utf-8 -*-
"""Uri_1009.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

nome=input()
salario=float(input())
vendas=float(input())
TOTAL=(vendas*(15/100)+salario)
print("TOTAL = R$ {:.2f}".format(TOTAL))