# -*- coding: utf-8 -*-
"""Uri_1015.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

x1,y1=input().split()
x2,y2=input().split()
x1=float(x1)
x2=float(x2)
y1=float(y1)
y2=float(y2)
distancia=((x2-x1)**2+(y2-y1)**2)**(1/2)
print("{:.4f}" .format(distancia))