# -*- coding: utf-8 -*-
"""Uri_1066.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/182zlSpotEVdt-OZq4eItrQiJT2kMSUSV
"""

par=0
imp=0
pos=0
neg=0
for i in range(5):
  num=float(input())
  if num%2==0:
    par+=1
  if num%2!=0:
    imp+=1
  if num>0:
    pos+=1
  if num<0:
    neg+=1
print("{} valor(es) par(es)".format(par))
print("{} valor(es) impar(es)".format(imp))
print("{} valor(es) positivo(s)".format(pos))
print("{} valor(es) negativo(s)".format(neg))

