# -*- coding: utf-8 -*-
"""Uri_1013.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

a,b,c=input().split()
a=int(a)
b=int(b)
c=int(c)
maiorAB=(a+b+abs(a-b))/2
maiorABC=int((maiorAB+c+abs(maiorAB-c))/2)
print("{} eh o maior".format(maiorABC))