# -*- coding: utf-8 -*-
"""Uri_1008.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

numero=int(input())
horas=int(input())
valor=float(input())
salario=float(horas*valor)
print("NUMBER =",numero)
print("SALARY = U$ {:.2f}".format(salario))