# -*- coding: utf-8 -*-
"""Uri_1067.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/182zlSpotEVdt-OZq4eItrQiJT2kMSUSV
"""

n=int(input())
i=1
while(i<=n):
	if(i%2!=0):
		print(i)
	i=i+1

