# -*- coding: utf-8 -*-
"""Uri_1051.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

sal=float(input())
if sal<=2000.00:
    print("Isento")
if 2000.01<=sal<=3000.00:
    sal1=(sal-2000.00)
    imp=sal1*(8/100)
    print("R$ {:.2f}".format(imp))
if 3000.01<=sal<=4500.00:
    sal1=(sal-3000.01)
    imp=(sal1*(18/100))+(1000*(8/100))
    print("R$ {:.2f}".format(imp))
if sal>4500.00:
    sal1=sal-4500.00
    imp=(sal1*(28/100))+(1500*(18/100))+(1000*(8/100))
    print("R$ {:.2f}".format(imp))