# -*- coding: utf-8 -*-
"""Uri_1005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

A=float(input())
B=float(input())
MEDIA=((A*3.5)+(B*7.5))/11
print("MEDIA = %.5f" % MEDIA)