# -*- coding: utf-8 -*-
"""Uri_1073.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HVuUV0P4lfD2K12nDpHlus7ibCikFqWG
"""

N=int(input())
for i in range(1,N+1):
    if i%2==0:
        print("{}^{} = {}".format(i,2,i**2))