# -*- coding: utf-8 -*-
"""Uri_1020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

ida=input()
ida=int(ida)
a=ida//365
m=(ida%365)//30
d=ida-(a*365)-(m*30)
print(a,"ano(s)")
print(m,"mes(es)")
print(d,"dia(s)")