# -*- coding: utf-8 -*-
"""Uri_1003.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

A = int(input())
B = int(input())
SOMA = A + B
print('SOMA =', SOMA)