# -*- coding: utf-8 -*-
"""Uri_1016.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

dist=int(input())
temp=int(dist*2)
print('{} minutos'.format(temp))