# -*- coding: utf-8 -*-
"""Uri_1065.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Qrvmb4glToU91guUE24KWrBpXKfLmgm
"""

lista=[]
for i in range(1,6):
  n=float(input())
  if n%2==0:
    lista.append(n)
    num=len(lista)
print("{} valores pares".format(num))