# -*- coding: utf-8 -*-
"""Uri_1040.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

n1,n2,n3,n4=input().split()
media=((float(n1)*2)+(float(n2)*3)+(float(n3)*4)+(float(n4)*1))/10
print("Media: {:.1f}".format(media))
if (media>=7.0):
    print("Aluno aprovado.")
if (media<5.0):
    print("Aluno reprovado.")
if (media>=5.0) and (media<=6.9):
    print("Aluno em exame.")
    nota=float(input())
    print("Nota do exame: {:.1f}".format(nota))
    media2=(nota+media)/2
    if (media2>=5.0):
        print("Aluno aprovado.")
        print("Media final: {:.1f}".format(media2))
    if (media2<=4.9):
        print("Aluno reprovado.")
        print("Media final: {:.1f}".format(media2))