# -*- coding: utf-8 -*-
"""Uri_1042.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

a,b,c=input().split()
a=int(a)
b=int(b)
c=int(c)
if a<b<c:
    print("""{}
{}
{}""".format(a,b,c))
elif a<c<b:
    print("""{}
{}
{}""".format(a,c,b))
elif b<c<a:
    print("""{}
{}
{}""".format(b,c,a))
elif b<a<c:
    print("""{}
{}
{}""".format(b,a,c))
elif c<b<a:
    print("""{}
{}
{}""".format(c,b,a))
elif c<a<b:
    print("""{}
{}
{}""".format(c,a,b))
print()   
print("""{}
{}
{}""".format(a,b,c))