# -*- coding: utf-8 -*-
"""Uri_1006.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

A=float(input())
B=float(input())
C=float(input())
MEDIA=((A*2)+(B*3)+(C*5))/10
print("MEDIA = %.1f" % MEDIA)