# -*- coding: utf-8 -*-
"""Uri_1059.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Qrvmb4glToU91guUE24KWrBpXKfLmgm
"""

for i in range(1,101):
    if i%2==0:
        print(i)