# -*- coding: utf-8 -*-
"""Uri_1046.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

hi,hf=input().split()
hi=int(hi)
hf=int(hf)
if hi<hf:
    duracao=hf-hi
else:
    duracao=(24-hi)+hf
print("O JOGO DUROU {} HORA(S)".format(duracao))