# -*- coding: utf-8 -*-
"""Uri_1041.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

x,y=input().split()
x,y=float(x),float(y)
if x==0:
    if y==0:
        print("Origem")
    else:
        print("Eixo Y")
if y==0:
    if x!=0:
        print("Eixo X")
if x>0 and y>0:
    print("Q1")
if x<0 and y>0:
    print("Q2")
if x<0 and y<0:
    print("Q3")
if x>0 and y<0:
    print("Q4")