# -*- coding: utf-8 -*-
"""Uri_1002.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

pi=3.14159
r=float(input())
A=pi*(r**2)
print(f'A={A:.4f}')