# -*- coding: utf-8 -*-
"""Uri_1045.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

A,B,C=input().split()
A=float(A)
B=float(B)
C=float(C)

if A<B:
    V=A
    A=B
    B=V
if B<C:
    V=B
    B=C
    C=V
if A<B:
    V=A
    A=B
    B=V

if A>=(B+C):
    print("NAO FORMA TRIANGULO")
else:
    if (A*A)==(B*B)+(C*C):
        print("TRIANGULO RETANGULO")
    if (A*A)>(B*B)+(C*C):
        print("TRIANGULO OBTUSANGULO")
    if (A*A)<(B*B)+(C*C):
        print("TRIANGULO ACUTANGULO")
    if (A==B==C):
        print("TRIANGULO EQUILATERO")
    if (A==B!=C) or (B==C!=A) or (A==C!=B):
        print("TRIANGULO ISOSCELES")