# -*- coding: utf-8 -*-
"""Uri_1052.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Qrvmb4glToU91guUE24KWrBpXKfLmgm
"""

mes=int(input())
if mes==1:
    print("January")
elif mes==2:
    print("February")
elif mes==3:
    print("March")
elif mes==4:
    print("April")
elif mes==5:
    print("May")
elif mes==6:
    print("June")
elif mes==7:
    print("July")
elif mes==8:
    print("August")
elif mes==9:
    print("September")
elif mes==10:
    print("October")
elif mes==11:
    print("November")
elif mes==12:
    print("December")