# -*- coding: utf-8 -*-
"""Uri_1038.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

cod,qtd=input().split()
if cod=="1":
    print("Total: R$ {:.2f}".format(float(qtd)*4.00))
if cod=="2":
    print("Total: R$ {:.2f}".format(float(qtd)*4.50))
if cod=="3":
    print("Total: R$ {:.2f}".format(float(qtd)*5.00))
if cod=="4":
     print("Total: R$ {:.2f}".format(float(qtd)*2.00))
if cod=="5":
    print("Total: R$ {:.2f}".format(float(qtd)*1.50))