# -*- coding: utf-8 -*-
"""Uri_1070.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/182zlSpotEVdt-OZq4eItrQiJT2kMSUSV
"""

x=int(input())
for i in range(1,13):
  if x%2!=0:
    print(x)
  x+=1