# -*- coding: utf-8 -*-
"""Uri_1043.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

a,b,c=input().split()
a=float(a)
b=float(b)
c=float(c)
if a>b-c and a<b+c and b>a-c and b<a+c and c>a-b and c<a+b:
    perimetro=a+b+c
    print("Perimetro = {:.1f}".format(float(perimetro)))
else:
    area=((a+b)*c)/2
    print("Area = {:.1f}".format(float(area)))