# -*- coding: utf-8 -*-
"""Uri_1014.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdGOyqJlqieRjCr39f_lqvoZvXPc3yHn
"""

X=int(input())
Y=float(input())
valor=X/Y
print("%0.3f km/l" %valor)